name: Build draft PDF

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  paper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build paper draft
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          paper-path: paper.md

      - name: Upload draft PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: paper.pdf
